server:
  port: 8082

spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off
  profiles:
    active: dev

logging:
  level:
    ru.ilysenko.tinka: INFO
    ru.tinkoff.invest: DEBUG
  pattern:
    console: '%clr( %d{HH:mm:ss}){cyan}  %clr(%m){faint}%n'

tinkoff:
  invest:
    client:
      useSandbox: true
      sandboxToken: t.123456
      exchangeToken: t.654321
