spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off
  profiles:
    active: dev

logging:
  level:
    ru.ilysenko.tinka: DEBUG
    ru.tinkoff.invest: DEBUG
  pattern:
    console: '%clr( %d{HH:mm:ss}){cyan}  %clr(%m){faint}%n'

client:
  useSandbox: true
  sandboxToken: 56894568923sd
  exchangeToken: 435345sdfsd32
