tinkoff:
  invest:
    client:
#      token: t.YIQXsKrsdjqGPJxUs-kyR-AS9UY6rV8EQNAJ2SMH8KuPzdIHuxGNMis86AT1WcL11Xmw5gP6CMINJV3rzaUHAA
      token: t.6AkC7PZkMrpl2Hxd4aZXCLqMrmYcsPqh2jaNS3ZcnizKJ6WbzIBgMR2aNn4LTbrga7dDM0rVZldKFGRUWBouLw

spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off

server:
  port: 8082

logging:
  level:
    ru.ilysenko.tinka: TRACE
    ru.tinkoff.invest: TRACE
  pattern:
    console: '%clr( %d{HH:mm:ss}){cyan}  %clr(%m){faint}%n'