tinkoff:
  invest:
    client:
      token: t.123456

spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off

server:
  port: 8082

logging:
  level:
    ru.ilysenko.tinka: INFO
    ru.tinkoff.invest: DEBUG
  pattern:
    console: '%clr( %d{HH:mm:ss}){cyan}  %clr(%m){faint}%n'